// Mudaala - all UI copy in one place.
//
// The voice: plain, direct English as spoken in Kampala. Short sentences.
// No slogans, no small-caps eyebrow labels, no em dashes, and none of the
// template words (seamless, empower, discover, unlock). Buttons say what
// they do: Call, WhatsApp, Post an ad.
//
// Server and client components both import from here; the file must stay
// free of imports so it can load in any runtime.

export const copy = {
  app: {
    name: 'Mudaala',
    tagline: 'Buy and sell near you',
    metaTitle: 'Mudaala: buy and sell near you',
    metaDescription:
      'Mudaala is a local marketplace for Uganda. Sellers post what they sell and what they need. Buyers call or message them directly by phone or WhatsApp.',
    footerLine: 'Buy and sell near you',
    footerNote: 'Shops post what they sell. You call or message them directly.',
  },

  nav: {
    home: 'Home',
    browse: 'Browse',
    post: 'Post',
    postAd: 'Post an ad',
    myListings: 'My listings',
    savedSearches: 'Saved searches',
    notifications: 'Alerts',
    account: 'My business',
    settings: 'Settings',
    signIn: 'Sign in',
    signOut: 'Sign out',
    basket: 'Basket',
    accountAndProfile: 'Account and profile',
    signedOut: 'Signed out',
    helpNeed: 'Need help?',
    helpWhatsApp: 'Chat on WhatsApp',
    helpPrompt: 'Hi Mudaala, I need some help.',
  },

  common: {
    call: 'Call',
    whatsapp: 'WhatsApp',
    postAnAd: 'Post an ad',
    browse: 'Browse',
    browseAll: 'Browse all listings',
    browseListings: 'Browse listings',
    browseEverything: 'Browse everything',
    clearAll: 'Clear all',
    clear: 'Clear',
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    copy: 'Copy',
    copied: 'Copied',
    share: 'Share',
    prev: 'Prev',
    next: 'Next',
    tryAgain: 'Try again',
    loading: 'Loading…',
    askPrice: 'Ask for price',
    askSeller: 'Ask seller',
    negotiable: 'Negotiable',
    negotiableShort: 'neg.',
    budget: 'Budget',
    price: 'Price',
    was: 'was',
    all: 'All',
    anyDistrict: 'All districts',
    anyCategory: 'All categories',
    anyUnit: 'Any unit',
    anywhere: 'Anywhere',
    anywhereLabel: 'Anywhere',
    offer: 'OFFER',
    request: 'REQUEST',
    errorTitle: 'Something went wrong',
    connectionHint: 'Check your connection and try again.',
    photoPending: 'Photo coming from the seller',
  },

  // The listing card (row on mobile, compact block in desktop grids).
  card: {
    openAria: (title: string) => `Open listing: ${title}`,
    visitShopAria: (shop: string) => `Visit shop: ${shop}`,
    callAria: (shop: string, title: string) => `Call ${shop} about ${title}`,
    whatsappAria: (shop: string, title: string) => `WhatsApp ${shop} about ${title}`,
    addCartAria: (title: string) => `Add ${listingTitle(title)} to cart`,
    photoCount: (n: number) => `+${n}`,
  },

  browse: {
    heading: 'Buy and sell near you',
    sub: 'Shops post what they sell and what they need. You call or message them direct.',
    searchPlaceholder: 'Search matooke, charcoal, cement…',
    searchLabel: 'Search listings',
    filters: 'Filters',
    openFiltersAria: 'Open filters',
    filterHeading: 'Filters',
    filterSub: 'Narrow results by type, category, location and price.',
    type: 'Type',
    category: 'Category',
    district: 'District',
    minPrice: 'Min price',
    maxPrice: 'Max price',
    priceUnit: 'Price unit',
    reset: 'Reset',
    showResults: 'Show results',
    sortLabel: 'Sort results',
    sortNewest: 'Newest first',
    sortNearest: 'Nearest first',
    sortPriceAsc: 'Price: low to high',
    sortPriceDesc: 'Price: high to low',
    nearMe: 'Near me',
    nearMeLocating: 'Finding you…',
    saveSearch: 'Save this search',
    loved: 'Loved',
    lovedAriaOn: 'Showing your loved items',
    lovedAriaOff: (n: number) => `Show your loved items${n > 0 ? ` (${n})` : ''}`,
    nearDenied:
      'Location is off. Allow it when the browser asks and shops closest to you come first. You can still browse everything.',
    resultsFound: (n: number, page?: { page: number; pageCount: number }) =>
      `${n} ${n === 1 ? 'listing' : 'listings'} found${page && page.pageCount > 1 ? ` · page ${page.page} of ${page.pageCount}` : ''}`,
    emptyFilteredTitle: 'Nothing matches',
    emptyFilteredSub: 'Try fewer filters or a different word.',
    emptyTitle: 'No ads here yet. Be the first to post.',
    emptySub: 'Post what you sell or what you need. A phone line is all buyers need to reach you.',
    clearSearchFilters: 'Clear search and filters',
    codeFinding: (code: string) => `Finding the shop for ${code}…`,
    codeShopLabel: (code: string) => `Shop for code ${code}`,
    codeError: 'Could not check that code. Check the number with the shop.',
    codePrompt: 'Scan the code, or type it into search like a till number.',
    featuredShop: 'From these results',
    featuredCallAria: (shop: string) => `Call ${shop}`,
    featuredCodeHint: 'Scan, or type the code in search, to see the whole shop.',
    lovedShelfCount: (n: number) =>
      `Your shortlist · ${n} ${n === 1 ? 'item' : 'items'}, newest first. It lives on this phone.`,
    lovedEmptyTitle: 'Nothing loved yet',
    lovedEmptySub:
      'Tap the heart on any item and it waits here for later. The shortlist lives on this phone, just like the basket.',
    lovedUnavailable: (n: number) =>
      n === 1 ? '1 loved item is no longer available:' : `${n} loved items are no longer available:`,
    lovedForget: 'tap the heart to forget it',
    loadError: 'Could not load listings',
    lovedLoadError: 'Could not load your loved items',
  },

  home: {
    welcomeTitle: 'Welcome to Mudaala',
    welcomeSub:
      'Sign in to see your saved searches, new matches, the offers around you and how prices are moving. Everything you post and follow, on one page.',
    signIn: 'Sign in',
    browseMarket: 'Browse the market',
    loadError: 'Your dashboard could not load. Check your connection and try again.',
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    dashSub: 'Your market, at a glance.',
    statSavedSearches: 'Saved searches',
    statActiveListings: 'Active listings',
    statNewMatches: 'New matches',
    statLastUpdated: 'Last updated',
    freshnessTitle: 'Refresh old ads',
    freshnessBody: (n: number) =>
      n === 1
        ? '1 of your ads has not been refreshed in over a week. Refreshing puts it back at the top of Browse.'
        : `${n} of your ads have not been refreshed in over a week. Refreshing puts them back at the top of Browse.`,
    freshnessItemAge: (n: number) => `Last refreshed ${n === 1 ? '1 day' : `${n} days`} ago`,
    renew: 'Renew',
    renewing: 'Refreshing…',
    moreInListings: (n: number) => `+${n} more in My listings`,
    bestOffers: 'Offers near you',
    change: 'Change',
    chooseLocation: 'Choose a location',
    chooseLocationSub: 'Offers are ranked around this place. Your shop area is the default.',
    pickDistrict: 'Pick a district',
    myShopArea: (area: string) => `${area} (my shop area)`,
    useMyShopArea: 'Use my shop area',
    showOffers: 'Show offers',
    noOffersTitle: 'No offers here yet',
    noOffersIn: (county: string | null) => (county ? `Nothing active in ${county} right now.` : 'Nothing active right now.'),
    savedSearchesTitle: 'Saved searches',
    savedSearchesTotal: (n: number) => `${n} total`,
    noSavedTitle: 'No saved searches yet',
    noSavedSub: 'Save a search on Browse and new matches will reach you here.',
    matches: (n: number) => `${n} ${n === 1 ? 'match' : 'matches'}`,
    viewAllSaved: (n: number) => `View all ${n} saved searches`,
    savedCorrupt: 'This saved search is corrupted. Delete and recreate it.',
    trendsTitle: 'Price trends',
    trendsSub: 'Median asking price, last 7 days, in the categories you post or save most.',
    trendsNotEnoughTitle: 'Not enough listings yet',
    trendsNotEnoughSub: (min: number) =>
      `Price lines appear once ${min}+ active listings share a category and unit. The market builds them up a little every day.`,
    trendsMoreData: (n: number) => ` · ${n} of your categories need more data before a line can be drawn.`,
    moversTitle: 'Moving this week',
    moversSub: 'Market prices that shifted most in the last 7 days, across all Mudaala shops.',
    moversPerUnit: (unit: string) => `per ${unit}`,
    moverUpWord: 'up',
    moverDownWord: 'down',
    moversRowAria: (label: string, unit: string, price: string, pct: number, n: number, word: string) =>
      `${label} per ${unit}: median ${price}, ${word} ${pct} percent this week, from ${n} listings`,
    moversSource: (min: number) =>
      `Median asking prices from live Mudaala listings. A number needs ${min} or more listings behind it before it counts.`,
    updated: (t: string) => `Updated ${t}`,
    statNotYet: 'Not yet',
  },

  listing: {
    backToBrowse: 'Back to browse',
    loadError: 'Could not load this listing',
    description: 'Description',
    details: 'Details',
    quantity: 'Quantity',
    location: 'Location',
    updated: 'Updated',
    views: 'Views',
    posted: (date: string, expiry: string) => `Posted ${date} · ${expiry}`,
    buyFrom: 'You would be buying from',
    sellTo: 'You would be selling to',
    fulfilledNote: 'The owner has marked this listing as fulfilled.',
    expiredNote: 'This ad has expired and may no longer be available.',
    archivedNote: 'The owner has archived this ad.',
    contact: (shop: string) => `Contact ${shop}`,
    addToCart: 'Add to cart',
    addedToCart: 'Added to cart',
    directions: 'Get directions',
    directionsHint: '(Google Maps, for pickup)',
    directionsAria: (place: string) => `Get directions to ${place}`,
    // The number is a tap, not markup: scrapers sweeping ad pages get nothing,
    // a real buyer taps once and sees what any ad always showed.
    showNumber: 'Show number',
    showNumberHint: 'The number stays out of the page until you ask for it.',
    showNumberLoading: 'Showing…',
    showNumberError: 'Could not load the number.',
    retry: 'Try again',
    shareAria: 'Share this ad',
    aboutSeller: 'About the seller',
    aboutSellerRequest: 'Who is buying',
    shopCodeLabel: 'Shop code',
    shopCodeHint: 'Type it into Mudaala search to find this shop again.',
    footerHint: 'Looking for something else?',
    memberSince: (d: string) => `Member since ${d}`,
    visitShop: (shop: string) => `Visit ${shop}'s shop`,
    visitShopAria: (shop: string) => `Visit ${shop}'s shop`,
    hours: (h: string) => `Hours: ${h}`,
    noPhotoNote: 'No photo yet. Ask the seller for details.',
    photoSwipe: (n: number) => `${n} photos · swipe`,
    photosOfAria: (title: string) => `Photos of ${title}`,
    photoAlt: (title: string, i: number, n: number) => `${title}, photo ${i + 1} of ${n}`,
    // Owner prompt on their own photo-less ads.
    addPhotoTitle: 'Add a photo: ads with photos get more calls',
    addPhotoCta: 'Add photo',
    // Seller voice, used when the shop has no description.
    noStory: 'This shop has not written anything yet. The ads and the phone line speak for it.',
  },

  shop: {
    backToBrowse: 'Back to browse',
    loadError: 'Could not load this shop',
    ownerStrip: 'This is your shop. This is exactly what buyers see.',
    editShop: 'Edit shop',
    coverTileAria: (shop: string) => `Shop cover photo coming soon for ${shop}`,
    phoneConfirmed: 'Phone confirmed',
    profileComplete: 'Complete shop profile',
    profileProgress: (n: number) => `Profile ${n}/5 complete`,
    writeAbout: 'Write it',
    writeAboutPrompt: 'Add a few words about your shop. Buyers read them right here.',
    contactOwnerNote: 'Buyers tap these. The call or message lands straight on your phone.',
    contactBuyerNote: 'Straight to the shop, no middleman. Your call or message rings their phone.',
    findAgain: 'Find this shop again',
    findAgainHint: 'Scan the code, or type it into Mudaala search like a till number.',
    posterTitle: 'Your shop QR poster',
    posterSub: 'Print it and put it where customers stand. Anyone who scans lands right here. No typing, no searching.',
    posterCodeNote: (code: string) =>
      `Your code is ${code}. It never changes, so old posters keep working. Customers can type it into the Mudaala search too.`,
    posterShow: 'Show poster and print',
    posterShare: 'Share on WhatsApp',
    posterHint: 'Poster preview. Print it and stick it up.',
    posterScan: 'Scan to shop on Mudaala',
    posterCodeCaption: 'Shop code',
    posterRescan: "Can't scan? Type the code in Mudaala search.",
    catalogue: (n: number) => `In this shop (${n})`,
    catalogueNote: 'Posted by the shop. Prices are theirs, not ours.',
    emptyOwnerTitle: 'Nothing on the shelf right now',
    emptyOwnerSub: 'Buyers are landing on this page. Post a listing and the shelf fills up.',
    emptyBuyerSub:
      'This shop has not posted anything yet. The stall may still have stock. Call or WhatsApp above, or browse other shops.',
    posterCallUs: (phone: string) => `Call: ${phone}`,
    shareTextOwner: (shop: string, code: string, url: string) => `Find ${shop} on Mudaala. Our code is ${code}. ${url}`,
    shareTextBuyer: (shop: string, code: string, url: string) => `Found ${shop} on Mudaala. Shop code ${code}. ${url}`,
    qrAria: (shop: string) => `QR code for ${shop}'s shop`,
    shopCodeUnchanged: (code: string) => code,
  },

  // Your data - export it or leave with it. The delete flow says the whole
  // truth BEFORE the password box, because this one cannot be undone.
  accountData: {
    title: 'Your data',
    exportLabel: 'Download my data',
    exportHint: 'One JSON file: your account, shop, ads, saved searches, alerts and reports.',
    exportFailed: 'The download did not start. Check your connection and try again.',
    deleteLabel: 'Delete my account',
    deleteWarningTitle: 'Delete your account?',
    deleteWarningBody:
      'This removes everything: your account, your shop, all your ads and their photos, your saved searches and alerts. Reports you filed stay, but no longer carry your name. This cannot be undone.',
    deletePasswordLabel: 'Type your password to confirm',
    deleteCta: 'Delete everything',
    deleteCancel: 'Keep my account',
    deleteWrongPassword: 'That password does not match. Nothing was deleted.',
    deleteFailed: 'The account could not be deleted right now. Try again.',
    deleteSuccessTitle: 'Account deleted',
    deleteSuccessBody: 'Everything is gone. You are signed out, and we are sorry to see you go.',
  },

  publish: {
    signInTitle: 'Sign in to post an ad',
    signInSub: 'An account keeps your ads, saved searches and alerts in one place. It takes less than a minute.',
    signInCta: 'Sign in or create account',
    keepBrowsing: 'Keep browsing',
    title: 'Post an ad',
    editTitle: 'Edit ad',
    sub: 'Say clearly what you sell or what you need.',
    iWantTo: 'I want to…',
    sell: 'Sell something (OFFER)',
    buy: 'Ask for something (REQUEST)',
    whatExactly: 'What exactly?',
    titlePlaceholderOffer: 'e.g. Copper scrap 99% clean',
    titlePlaceholderRequest: 'e.g. Need wheat flour, 50 bags weekly',
    description: 'Description',
    descPlaceholderOffer: 'Condition, packaging, collection or delivery, who should buy…',
    descPlaceholderRequest: 'Specification, how much, how often, who should contact you…',
    photos: 'Photos',
    photosHint: 'Ads with photos get more calls. Buyers trust what they can see.',
    oldPrice: 'Old price (optional)',
    oldPriceHint: 'shows as a discount',
    per: 'Per',
    unitPlaceholder: 'Unit',
    priceNegotiable: 'Price is negotiable',
    quantity: 'Quantity available',
    area: 'Area or town (optional)',
    contactPhone: 'Contact phone',
    whatsapp: 'WhatsApp (optional)',
    whatsappHint: 'Leave empty if same as phone',
    submit: 'Post ad',
    submitting: 'Posting…',
    saveChanges: 'Save changes',
    saving: 'Saving…',
    publishedToast: 'Ad posted',
    publishedToastSub: 'Buyers and sellers can now find it in search.',
    failedToast: 'Could not post the ad',
  },

  alerts: {
    signInTitle: 'Sign in to see alerts',
    signInSub: 'Alerts appear here when new listings match your saved searches, and when your own ads are expiring or expired.',
    emptyTitle: 'No alerts yet',
    emptySub: 'Save a search on Browse and you will be alerted here when a matching listing is posted.',
    goSaved: 'Go to saved searches',
    clearTitle: 'Clear all alerts?',
    clearBody: 'Every alert, read and unread, is removed for good. Marking them read keeps the history; clearing does not.',
    clearKeep: 'Keep them',
    clearGo: 'Clear alerts',
    clearing: 'Clearing…',
  },

  saved: {
    signInTitle: 'Sign in to save searches',
    signInSub: 'Save the filters you use often and get an alert when a new listing matches.',
    emptyTitle: 'No saved searches yet',
    emptySub: 'Set filters on Browse and tap Save this search. We will alert you when new listings match.',
    sub: 'You get an alert on every new listing that matches.',
    checked: (t: string) => `checked ${t}`,
    apply: 'Apply',
    checkNow: 'Check now',
    remove: 'Remove',
  },

  basket: {
    title: 'Basket',
    signInTitle: 'Sign in to use the basket',
    signInSub: 'The basket keeps a running total of what you want to buy, right on this phone.',
    emptyTitle: 'Your basket is empty',
    emptySub: 'Tap the plus on any offer and it waits here with the running total.',
    browse: 'Browse offers',
    removed: (title: string) => `${title} removed`,
    undo: 'Undo',
    iconAria: (n: number) => `Basket, ${n} ${n === 1 ? 'item' : 'items'}`,
    topBarHint: 'Your cart collects as you shop. Pay from the basket up in the top bar when you are ready.',
    listCapHint: 'A shop list holds at most 20 items. Open the basket and remove something first.',
    viewSubOne: 'Your list lives on this phone. Pay the seller here, or send the list on WhatsApp.',
    viewSubMany: 'Your list lives on this phone. Pay or message each seller, shop by shop. Sellers only see their own list.',
    itemsOnList: (n: number) => `${n} ${n === 1 ? 'item' : 'items'} on your list`,
    shopListAria: (name: string) => `Basket for ${name}`,
    openShopAria: (name: string) => `Open shop: ${name}`,
    openLineAria: (title: string) => `Open listing: ${title}`,
    oneLessAria: (title: string) => `One less ${title}`,
    oneMoreAria: (title: string) => `One more ${title}`,
    removeLineAria: (title: string) => `Remove ${title} from this list`,
    undoAria: (title: string) => `Put ${title} back in the basket`,
    priceOnAsking: 'Price on asking',
    goneRemoved: 'Removed from Mudaala. Take it off your list.',
    goneUnavailable: 'No longer available. The seller may have sold out.',
    staleNoneNote: 'Nothing on this list is available right now. Remove the items or check the shop later.',
    staleSomeNote: (n: number, total: number) =>
      `${n} of ${total} items will NOT be included. They are no longer available.`,
    estimateNote: 'estimate. The seller confirms the final total.',
    nothingReadyToPay: 'Nothing ready to pay for',
    sendList: 'Send list on WhatsApp',
    sendListAria: (n: number, shop: string) => `Send your list of ${n} items to ${shop} on WhatsApp`,
    nothingToSend: 'Nothing to send',
    noWhatsappNote: 'This shop has no WhatsApp on the listing. Call with your list instead.',
    callWithList: 'Call with list',
    callWithListAria: (shop: string) => `Call ${shop} about your list`,
    clearList: 'Clear this list',
    statSellers: 'Sellers',
    statItems: 'Items',
    statTotal: 'Estimated total',
    totalMixed: 'Each list shows its own total',
    waitingOne: '1 seller is waiting for their list.',
    waitingMany: (n: number) => `${n} sellers are waiting for their list.`,
    waitingNone: 'Every seller has their list.',
    markDone: 'Mark as done',
    markDoneAria: (shop: string) => `Mark the ${shop} list as done`,
    doneChip: 'Done',
    doneUndoAria: (shop: string) => `The ${shop} list is marked as done. Tap to undo`,
  },

  // The cart: the tray that follows the buyer while they shop, on every
  // screen. Desktop (xl+) docks it as a side strip and side panel; phones
  // get a bar above the bottom nav that opens a bottom sheet. It only
  // collects - no comms and no money in it. The basket (the icon in the
  // top bar) is where final decisions happen: pay each seller or send the
  // list. Two names on purpose, two icons so the eye never mixes them up.
  cart: {
    title: 'Cart',
    iconAria: (n: number) => `Cart, ${n} ${n === 1 ? 'item' : 'items'}`,
    itemsLabel: (n: number) => `${n} ${n === 1 ? 'item' : 'items'}`,
    railAria: 'Your cart',
    hideRail: 'Hide the cart',
    closeSheet: 'Close the cart',
    emptyTitle: 'Your cart is empty',
    emptySub: 'Tap the plus on any offer and it waits here while you shop.',
    openBasket: 'Open basket to pay',
  },

  // The sidebar shop-code card: a buyer types the code from a shop's poster
  // (or their WhatsApp status) and lands straight in that shop.
  codeCard: {
    title: 'Have a shop code?',
    hint: 'Type it like a till number and land in the shop.',
    placeholder: 'MD-2623',
    go: 'Find the shop',
    inputAria: 'Shop code',
    badFormat: 'A shop code looks like MD-2623. You will find it on the shop poster or in their WhatsApp status.',
  },

  // The mobile-money pay sheet. Mudaala never touches money and never sees
  // the result: the sheet hands the buyer the shop's own code (or personal
  // number) and the dial string, and the telco's confirmation screen does
  // the name check. Every line here is the honest version of a checkout.
  pay: {
    open: 'Pay by mobile money',
    openAria: (shop: string) => `Pay ${shop} by mobile money`,
    titleMerchant: (shop: string) => `Pay ${shop} by mobile money`,
    titlePersonal: (shop: string) => `Send ${shop} money`,
    // The name check, stated where the buyer is about to need it. The name
    // on the confirm screen is whatever the shop typed when it registered
    // the code, so it can honestly differ from the shop name. When the shop
    // states that name, the buyer compares SCREEN to SHEET. When it does
    // not, we say so instead of pretending the shop name will show up.
    nameCheck: (network: string, registered: string) =>
      `When you confirm, ${network} shows the registered name. Expect ${registered}.`,
    nameCheckUnnamed: (network: string) =>
      `When you confirm, ${network} shows the name the shop gave the network. The shop has not told us that name, so check it looks right before you send.`,
    nameCheckPersonal: (shop: string) =>
      `On the confirmation screen, the name is the one the number is registered to. It can be the owner's name, not the shop. Not sure it is ${shop}? Ask first, then send.`,
    // The shop entered this itself - the app never vetted it, and says so.
    codeLabel: 'Merchant code',
    codeNote: 'The shop entered this code itself. Mudaala cannot verify it.',
    // The name the code brings, shown right under the code so the buyer
    // reads one against the other.
    confirmNameLabel: 'On the confirm screen, expect',
    confirmNameNote: 'The shop told us the name the code brings. If your screen shows a different name, do not send.',
    personalLabel: 'Shop number',
    estimate: (amount: string) => `Your list estimate is ${amount}. The seller confirms the final amount.`,
    noEstimate: 'Agree the amount with the seller first. You type it before you send.',
    dialLabel: 'Dial this',
    dialHint: 'Your dialer opens with everything typed in. Press call, then enter your PIN.',
    dialFallbackHint: 'Copy the dial code, paste it in your phone app, press call, then enter your PIN.',
    copyDial: 'Copy dial code',
    copyDialAria: 'Copy the full dial code',
    copyCode: 'Copy code',
    copyCodeAria: 'Copy the merchant code',
    copied: 'Copied',
    personalHint: (phone: string) => `Send to ${phone} on your money line, or in your mobile money app.`,
    mtnMenu: 'Or dial *165# and choose Pay Bill.',
    airtelMenu: 'Dial *185# and choose Pay Bill, then enter this code.',
    // The beera steady block. Short, warm, and load-bearing: this is the
    // product, not a legal checkbox.
    cautionTitle: 'Beera steady',
    cautionAgree: 'Agree the amount with the seller in your call or chat first.',
    cautionDirect: 'This sends money straight to the shop. Mudaala cannot reverse it or get it back.',
    cautionName: 'Check the name on the confirmation. If it is not the name this sheet expects, do not send.',
    close: 'Close',
    // Seller-side fields (shop profile form). The helper text is the honesty
    // contract at the point of entry: self-reported, buyer-visible, no fees.
    sellerNetworkLabel: 'Mobile money network',
    sellerCodeLabel: 'Merchant code',
    sellerNone: 'No merchant code',
    sellerNameLabel: 'Name the code brings',
    sellerNameHelper:
      'When a buyer pays this code, the network shows a name on their screen. Type that name exactly as it shows, even if it is not your shop name. Buyers check it before they send.',
    networkMTN: 'MTN MoMo Pay',
    networkAirtel: 'Airtel merchant',
    sellerNote:
      'Only enter your own merchant code. Buyers see it on your shop page and in their basket and pay you directly. Mudaala never touches the money.',
  },

  mySales: {
    title: 'My listings',
    count: (n: number) => `${n} ${n === 1 ? 'listing' : 'listings'}`,
    sub: 'Refresh to stay visible. Mark fulfilled when done.',
    signInTitle: 'Sign in to manage your ads',
    signInSub: 'Your ads, their status and expiry all live here once you sign in.',
    emptyTitle: 'You have no ads yet',
    emptySub: 'Post what you sell or what you need. It takes about a minute and buyers can find you right away.',
    postFirst: 'Post your first ad',
    refresh: 'Refresh',
    refreshIn: (h: number) => `Refresh in ${h}h`,
    refreshCooldown: (h: number) => `Available in ${h}h (24h cooldown)`,
    edit: 'Edit',
    markFulfilled: 'Mark fulfilled',
    repost: 'Repost',
    repostHint: 'Repost: restarts freshness and expiry',
    archive: 'Archive',
    delete: 'Delete',
    deleting: 'Deleting…',
    deleteConfirmTitle: 'Delete this listing?',
    deleteConfirmBody: (title: string) => `"${title}" will be removed permanently. This cannot be undone.`,
    deleteKeep: 'Keep it',
    deleteGo: 'Delete listing',
    refreshedToast: 'Ad refreshed',
    refreshedToastSub: (d: number) => `It now appears as fresh and expires in ${d} days.`,
    couldNotRefresh: 'Could not refresh',
    statusFulfilled: 'Marked as fulfilled',
    statusActive: 'Ad is active again',
    statusArchived: 'Ad archived',
    couldNotUpdate: 'Could not update the ad',
    deletedToast: 'Ad deleted',
    couldNotDelete: 'Could not delete',
    notActive: 'Not active',
  },

  empty: {
    // Plain-text empty states. No icon boxes, no illustrations.
    browseTitle: 'No ads here yet. Be the first to post.',
  },
}

// Titles arrive from sellers and may already carry punctuation; strip a
// trailing period so an interpolated sentence never doubles one up.
function listingTitle(title: string): string {
  return title
}

export default copy
